site_name: cell-data
site_url: https://cell-data.readthedocs.io/
repo_url: https://github.com/biobourne/cell-data
repo_name: biobourne/cell-data
edit_uri: edit/main/docs/

theme:
  name: readthedocs

nav:
  - 首页: index.md
